[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.7"
redis = "0.25.3"
rusqlite = "0.31.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
time = "0.3.36"
toml = "0.8.12"
xml-rs = "0.8.20"
